### ISSUE TITLE
The big 1.0 todo list ticket

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/worker#3]
Instead of opening an issue for every single thing I can think of that needs to be done for 1.0 (some of these are relatively minor and no discussion is needed), I'm opening this and I'm adding a big TODO list. If you want to discuss one of these, then open a new issue for it and link to it in the TODO list.

- [x] Write an integration test (and some unit tests where it makes sense). Unit tests are hard to write, since so many components are dependent on an external system such as RabbitMQ.
- [x] Pass the `context.Context` around everywhere.
- [x] Set up `SIGTERM` to cause a graceful shutdown.
- [x] Send state updates to travis-hub over RabbitMQ
- [x] Send log updates to travis-logs over RabbitMQ
